Add a tutorial of simple classification data
deepchecks/deepchecks pull request #1119
Opened 2022-03-27 16:45 UTC by noamzbr

#### Reference Issues/PRs

Closes #1048 

#### What does this implement/fix? Explain your changes.
A simple example of using the load_data method from the simple_classification_data module to quickly run checks over the dataset before even starting modeling.

2022-03-27 16:47 UTC, noamzbr commented
Attached is the resulting suite
[output.zip](https://github.com/deepchecks/deepchecks/files/8358063/output.zip)

2022-03-28 07:51 UTC, ItayGabbay requested changes

2022-03-28 07:51 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +Deepchecks Vision is built to enable validate your data and model, however complex your model and data may be. That
```suggestion
Deepchecks Vision is built to validate your data and model, however complex your model and data may be. That
```

2022-03-28 07:51 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +:doc:`**ClassificationData** </tutorials/vision/classification_tutorial>` or
```suggestion
`**ClassificationData** </tutorials/vision/classification_tutorial>` or
```

2022-03-28 07:51 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +:doc:`**DetectionData** </tutorials/vision/detection_tutorial>`. In the case of a simple classification task,
```suggestion
`**DetectionData** </tutorials/vision/detection_tutorial>`. In the case of a simple classification task,
```

2022-03-28 07:51 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +# Running Deepchecks' full suite
Shouldn't it be a regular title? (=============)

2022-03-28 07:51 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Same here?

2022-03-28 08:02 UTC, ItayGabbay approved these changes

2022-03-28 08:02 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +`**ClassificationData** </tutorials/vision/classification_tutorial>` or
```suggestion
`**ClassificationData** </tutorials/vision/examples/plot_classification_tutorial.html>`__ or
```

2022-03-28 08:02 UTC, ItayGabbay commented on docs/source/tutorials/vision/plot_simple_classification_tutorial.py
> +`**DetectionData** </tutorials/vision/detection_tutorial>`. In the case of a simple classification task,
```suggestion
`**DetectionData** </tutorials/vision/examples/plot_detection_tutorial.html>`. In the case of a simple classification task,
```

2022-03-28 08:56 UTC, merged