Weak segments performance
deepchecks/deepchecks pull request #1671
Opened 2022-06-20 15:14 UTC by Nadav-Barak

Resolves https://github.com/deepchecks/deepchecks/issues/1571

This is a big issue and so we will be uploaded and reviewed in parts for your connivance.

2022-06-20 16:51 UTC, matanper commented on deepchecks/utils/performance/partition.py
> +        data = dataframe.copy()
why copy?

2022-06-20 16:54 UTC, matanper commented on deepchecks/utils/performance/partition.py
> +            left_filter = DeepchecksFilter([lambda df, a=tree.threshold[node_idx]: df[node_to_feature[node_idx]] <= a])
`node_to_feature` might contain Nones won't this fail `node_to_feature[node_idx]] <= a`?

2022-06-20 16:57 UTC, matanper commented on deepchecks/utils/performance/partition.py
> +            left_filter = DeepchecksFilter([lambda df, a=tree.threshold[node_idx]: df[node_to_feature[node_idx]] <= a])
We use the filter like `dc_filter.filter(df)` where is the `a` parameter coming from?

2022-06-21 07:02 UTC, Nadav-Barak commented on deepchecks/utils/performance/partition.py
> +    def recurse(node_idx, filter_up_to_node):
No, its truncate (intersect) filters and in that way returns the "complex" filters equivalent to the leaves of the tree

2022-06-21 07:02 UTC, Nadav-Barak commented on deepchecks/utils/performance/partition.py
> +        data = dataframe.copy()
You are correct

2022-06-21 07:06 UTC, Nadav-Barak commented on deepchecks/utils/performance/partition.py
> +    def recurse(node_idx, filter_up_to_node):
as a list - each element in the list correspond to a leaf

2022-06-21 07:11 UTC, matanper commented on deepchecks/utils/performance/partition.py
> +    def recurse(node_idx, filter_up_to_node):
so the usage of `DeepchecksFilter` is confusing, I'd expect the function to return list of `DeepchecksFilter`s and not a single one

2022-06-21 07:33 UTC, nirhutnik requested changes

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +        List of functions which receive dataframe and return a filter on it. If None uses applies no filter
```suggestion
        List of functions that receive a DataFrame and return a filter on it. If None, no filter is applied
```

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +        if not filter_functions or len(filter_functions) == 0:
if len(filter_functions) == 0 is True, then "not filter_functions" will be True as well so redundant

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    filter_functions : Callable, default: None
```suggestion
    filter_functions : List[Callable], default: None
```

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    label : str, default = ''
Maybe have another default, like "filter" or something? Not critical.

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +            self.filter_func = filter_functions
Should be called "filter_functions" in self as well IMO

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    node_to_feature = [feature_names[i] if i != _tree.TREE_UNDEFINED else None for i in tree.feature]
If i is not an integer, give it another name

2022-06-21 07:33 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    """Extract the leaves from a sklearn tree and covert them into DeepchecksFilters.
In general - really awesome, but you need more documentation and explanations on this function so in the future, others will get what it's doing :)

2022-06-21 08:45 UTC, matanper approved these changes

2022-06-21 11:30 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    More specifically go over the tree from root to leaf and truncates (intersect) the relevant filters along the way.
```suggestion
    The function goes over the tree from root to leaf and concatenates (by intersecting) the relevant filters along the way.
```

2022-06-21 11:32 UTC, nirhutnik commented on deepchecks/utils/performance/partition.py
> +    The result is a list in which each element is the truncate path between the root to a different leaf.
```suggestion
    The function returns a list in which each element is a DeepchecksFilter representing the path between the root to a different leaf.
```

2022-06-21 14:48 UTC, merged