Segmentation docs and tests 1888
deepchecks/deepchecks pull request #1991
Opened 2022-09-07 22:47 UTC by nirhutnik

Added segmentation data tutorial
(will also have tests)

closes #1888

2022-09-10 16:22 UTC, nirhutnik commented
PDF of docs:
[Semantic Segmentation Tutorial — gallery-boilerplate documentation.pdf](https://github.com/deepchecks/deepchecks/files/9540849/Semantic.Segmentation.Tutorial.gallery-boilerplate.documentation.pdf)


Image that belongs there (missing in docs because of gallery-boilerplate bug):
![segmentation_5_examples](https://user-images.githubusercontent.com/92314933/189491869-ebaa15d4-a352-4e98-9e35-bb6b82828e4b.png)

2022-09-11 08:02 UTC, noamzbr reviewed
Cool! Added a few comments

Need to also mention segmentation in https://docs.deepchecks.com/stable/getting-started/welcome.html#computer-vision (Are there other places where we should mention this new task?)

2022-09-11 08:03 UTC, nirhutnik commented on deepchecks/vision/metrics_utils/semantic_segmentation_metrics.py
> +        scores_per_class = np.empty(max_class + 1)*np.nan
That all classes (that we know of) are there, yes.
This is done in other metrics as well

2022-09-11 08:05 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +Therefore, the common output of these tasks is an image of identical size to the input, with a vector for each pixel
Hmmm. I'm not sure about that. And not really sure how important that is 😅 
Can change to "a common output" if you want

2022-09-11 08:06 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# The model in this tutorial is used to detect different objects in images, based on the Pascal VOC dataset.
This refers to the model. The model is trained on Pascal VOC.

2022-09-11 08:07 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# .. image :: /_static/images/tutorials/segmentation_5_examples.png
It's the same, but for some reason that I didn't try to understand it doesn't show. This is like this in the detection tutorial as well so I just followed the same logic.

2022-09-11 08:07 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +print("Example output of a label shape from the dataloader ", batch[1][0])
Sure why not

2022-09-11 08:10 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# And observe the output:
Ummm not it's not?
![image](https://user-images.githubusercontent.com/92314933/189518025-d040e40c-2aaf-465a-b206-9a08eb7fe799.png)
Or did I misunderstand you?

2022-09-11 08:10 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +from deepchecks.vision.suites import full_suite
Honestly not sure. It won't be very interesting as this runs on COCO which is a very limited dataset.

2022-09-11 11:15 UTC, noamzbr commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# The model in this tutorial is used to detect different objects in images, based on the Pascal VOC dataset.
So from here it reads as if the images are based on Pascal VOC dataset, not the model.

2022-09-11 11:16 UTC, noamzbr commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +print("Example output of a label shape from the dataloader ", batch[1][0])
I mean, did you intend to show the shape or the data itself?
(I'm for the shape because the data is big)

2022-09-11 11:17 UTC, noamzbr commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +from deepchecks.vision.suites import full_suite
We don't want to showcase the full suite as we don't want people to use the full suite, and rather use the individual suite according to their stage in the model dev cycle.

2022-09-11 11:18 UTC, noamzbr commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# And observe the output:
Ahh because it's one code cell
my bad

2022-09-11 11:19 UTC, noamzbr commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +Therefore, the common output of these tasks is an image of identical size to the input, with a vector for each pixel
Maybe, not critical but caught my eye

2022-09-11 11:40 UTC, noamzbr requested changes
Important comment! Need to add SegmentationData to `deepchecks.vision.rst` index file

2022-09-13 07:49 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# The model in this tutorial is used to detect different objects in images, based on the Pascal VOC dataset.
Disagree but fixed

2022-09-13 07:49 UTC, nirhutnik commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +from deepchecks.vision.suites import full_suite
Changed to model_evaluation

2022-09-13 10:15 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# `official documentation <https://pytorch.org/vision/main/models/generated/torchvision.models.segmentation.lraspp_mobilenet_v3_large.html>`_.
```suggestion
# `official documentation <https://pytorch.org/vision/main/models/generated/torchvision.models.segmentation.lraspp_mobilenet_v3_large.html>`__.
```

2022-09-13 10:18 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2022-09-13 10:19 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +#     :alt: COCO images with segmenation labels
```suggestion
#     :alt: COCO images with segmentation labels
```

2022-09-13 10:19 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +:doc:`examples section  </checks_gallery/vision/index>`
```suggestion
:doc:`examples section  </checks_gallery/vision/index>`.
```

2022-09-13 10:21 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
> +# .. _observing_the_result:
```suggestion
# .. _vision_segmentation_tutorial__observing_the_result:
```

2022-09-13 10:24 UTC, shir22 commented on docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
>  If you just want to see the output of this tutorial, jump to :ref:`observing_the_result` section.
```suggestion
If you just want to see the output of this tutorial, jump to :ref:`vision_segmentation_tutorial__observing_the_result` section.
```
(added comment also in relevant place)

alternatively, you can do `#observing-the-results`__ or 'observing the results <#observing-the-results>`__
without defining the label (and delete the definition)

anyway labels are project-wide so if you do choose to leave it that way, we add a file-name-related prefix for uniqueness...

2022-09-13 10:38 UTC, noamzbr approved these changes
Approved pending on @shir22 s comments

2022-09-14 13:28 UTC, merged