Changed owners:
deepchecks/deepchecks pull request #1998
Opened 2022-09-10 20:14 UTC by nirhutnik

* Added Noam to approve docs
* Changed that devs are only responsible for tests/base instead of tests/ folder. This way, most changes in checks will not require devs (and can be either algo or devs).

2022-09-10 20:33 UTC, ItayGabbay requested changes

2022-09-10 20:33 UTC, ItayGabbay commented on .github/CODEOWNERS
> +/docs/ @ItayGabbay @shir22 @noambzr
It doesn't work. I think it's noamzbr?

2022-09-10 21:27 UTC, nirhutnik commented on .github/CODEOWNERS
> +/docs/ @ItayGabbay @shir22 @noambzr
You're right, thanks!

2022-09-11 07:14 UTC, noamzbr commented on .github/CODEOWNERS
> +tests/base @deepchecks/dev-team
Add also tests/serialization

2022-09-11 08:03 UTC, nirhutnik commented on .github/CODEOWNERS
> +tests/base @deepchecks/dev-team
Fixed

2022-09-11 08:33 UTC, noamzbr approved these changes

2022-09-11 14:58 UTC, ItayGabbay approved these changes

2022-09-11 14:58 UTC, merged