change output of performance overfit condition
deepchecks/deepchecks pull request #211
Opened 2021-11-30 15:16 UTC by benisraeldan

2021-12-01 08:50 UTC, noamzbr reviewed
Can you please update the performance overfit notebook so we can easily see the change?

2021-12-01 11:02 UTC, ItayGabbay requested changes

2021-12-01 11:02 UTC, ItayGabbay commented on deepchecks/checks/methodology/performance_overfit.py
> +                message = f'Found performance degradation in: {explained_failures[:-2]}'
I think the [:-2] is ugly. Maybe you can have the explaind_features as an array, and then join it?

```suggestion
                explained_failures = []
                for metric in failed_metrics:
                    explained_failures.append( f'{metric} (train={format_percent(train_metrics[metric])} '\
                                          f'test={format_percent(test_metrics[metric])}), ')
                message = f'Found performance degradation in: {','.join(explained_failures)}'
```

2021-12-02 12:32 UTC, ItayGabbay submitted a review, later dismissed

2021-12-07 08:22 UTC, ItayGabbay approved these changes

2021-12-07 08:34 UTC, merged