[DOCS] Update Welcome Docs
deepchecks/deepchecks pull request #2372
Opened 2023-03-06 17:30 UTC by shir22

2023-03-06 21:21 UTC, noamzbr requested changes
Actually one thing

2023-03-06 21:21 UTC, noamzbr commented on docs/source/getting-started/welcome.rst
> +        :link: /user-guide/vision/auto_quickstarts/plot_quickstart
```suggestion
        :link: /user-guide/vision/auto_quickstarts/index
```
This is broken

2023-03-07 07:37 UTC, ItayGabbay approved these changes

2023-03-07 07:37 UTC, ItayGabbay commented on docs/source/user-guide/tabular/quickstarts/plot_quickstart_in_5_minutes.py
> +# it won't appear in the Conditsions Summary since it no longer has any
```suggestion
# it won't appear in the Conditions Summary since it no longer has any
```

2023-03-07 12:17 UTC, noamzbr approved these changes

2023-03-07 15:08 UTC, merged