WIP: add model error analysis
deepchecks/deepchecks pull request #248
Opened 2021-12-12 15:43 UTC by benisraeldan

find top features that contribute to model error.

2021-12-14 14:06 UTC, noamzbr requested changes

2021-12-14 14:06 UTC, noamzbr commented on deepchecks/checks/performance/model_error_analysis.py
> +            Categorical features are represented as a violin graph. (x axis: category, y axis: error)
Not sure this is needed if graph is improved.

2021-12-14 14:06 UTC, noamzbr commented on deepchecks/checks/performance/model_error_analysis.py
> +        headnote = """<span>
This explanation should talk way more on what we're actually doing here, it's non trivial

2021-12-14 14:06 UTC, noamzbr commented on deepchecks/checks/performance/model_error_analysis.py
> +        dataset.validate_label()
Use only sample of data

2021-12-14 14:06 UTC, noamzbr commented on deepchecks/checks/performance/model_error_analysis.py
> +        error_model.fit(dataset.features_columns, y=score)
fit on train split of this dataset

2021-12-14 14:06 UTC, noamzbr commented on deepchecks/checks/performance/model_error_analysis.py
> +        error_fi = calculate_feature_importance(error_model, dataset)
evaluate fi on test split

2021-12-19 11:32 UTC, benisraeldan commented on deepchecks/checks/performance/model_error_analysis.py
> +        display_data = dataset.data.assign(score=score)
saves the data to display, which in this case is the dataset and score, it's only needed for the callbacks, will be removed for plotly

2021-12-22 17:15 UTC, closed without merging