Mlc 407
deepchecks/deepchecks pull request #364
Opened 2021-12-30 13:54 UTC by JKL98ISR

2021-12-30 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/deepchecks/deepchecks?pullRequest=364) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/deepchecks/deepchecks?pullRequest=364) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/deepchecks/deepchecks?pullRequest=364) it.</sub>

2022-01-02 14:20 UTC, ItayGabbay approved these changes

2022-01-02 14:23 UTC, JKL98ISR commented on deepchecks/checks/performance/performance_report.py
> +PR = TypeVar('PR', bound='PerformanceReport')
impossible

2022-01-02 14:33 UTC, matanper requested changes

2022-01-02 14:33 UTC, matanper commented on deepchecks/checks/performance/performance_report.py
> +                    for class_i, value in enumerate(score_result):
what about binary scorers?

2022-01-02 14:33 UTC, matanper commented on deepchecks/checks/performance/performance_report.py
> +                    for class_i, value in enumerate(score_result):
This won't work if the labels are not consecutive (for example the labels are 1,2,6)
use this: 
```
for class_score, class_value in zip(score_result, test_dataset.classes):
```

2022-01-02 15:09 UTC, matanper approved these changes

2022-01-02 15:20 UTC, merged