[issue-787] added device parameter to the vision checks context
deepchecks/deepchecks pull request #832
Opened 2022-02-08 15:45 UTC by yromanyshyn

resolves #787

2022-02-09 12:48 UTC, ItayGabbay commented
@yromanyshyn can you add tests?

2022-02-10 08:33 UTC, noamzbr reviewed
Two things:
1. Need to merge that with the recent refactor in vision base
2. Did we test that this work on gpu?

2022-02-10 09:58 UTC, yromanyshyn commented
@noamzbr 

>Two things:
> Need to merge that with the recent refactor in vision base
> Did we test that this work on gpu?

1. of course, currently I am writing tests for base vision classes and would like to add them to the current PR, in the near time I will push that changes.
2. I tried to run it on the collab and checks worked/ but that probably is not a sufficient enough test, will think about how to do it better.

2022-02-14 09:20 UTC, ItayGabbay commented on tests/vision/vision_conftest.py
> +
This downgrades the code coverage.

2022-02-14 10:28 UTC, ItayGabbay requested changes

2022-02-14 10:28 UTC, ItayGabbay commented on deepchecks/vision/base.py
>          # This is needed because in the vision package checks update their internal state with update, so it will be
What about adding the apply_to_tensor in the loop of the suite?

2022-02-14 10:41 UTC, ItayGabbay approved these changes

2022-02-14 10:58 UTC, merged